name: Bundle Update
description: A Buildkite plugin that runs bundle update
author: https://github.com/envato
requirements:
  - docker
configuration:
  properties:
    image:
      type: string
    update:
      type: boolean
  oneOf:
    - required:
      - update
  dependencies:
    image: [ update ]
