---

steps:

  - label: ":hammer: Test"
    plugins:
      docker-compose#v2.3.0:
        run: tests
    agents:
      queue: "${AGENT_QUEUE}"

  - label: ":sparkles: Lint"
    plugins:
      plugin-linter#v2.0.0:
        id: envato/bundle-update
    agents:
      queue: "${AGENT_QUEUE}"

  - label: ":shell: Shellcheck"
    plugins:
      shellcheck#v1.0.1:
        files:
          - hooks/**
          - commands/**
    agents:
      queue: "${AGENT_QUEUE}"
